import { TaggedQuestion } from './types';

/**
 * Cable Selection (Noob): What Affects Choosing a Cable Question Bank
 * Aligned with lesson 203-3L5C learning outcomes
 * Generated: 2026-03-02
 */

export const cableSelectionNoobWhatAffectsChoosingACableQuestions: TaggedQuestion[] = [
  {
    "id": 4016,
    "question": "What is the primary danger to a cable's insulation if it carries too much current?",
    "options": [
      "Overheating",
      "Voltage increase",
      "Magnetic cooling",
      "Color fading"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "current-rule",
      "conceptual"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Heat is the main limiting factor in cable selection. If a cable carries more current than it is designed for, the resistance in the copper causes it to overheat, which can damage the insulation."
  },
  {
    "id": 4017,
    "question": "Which of these is one of the five key factors an electrician must consider when selecting a cable?",
    "options": [
      "Environmental conditions",
      "The manufacturer's logo",
      "The color of the outer sheath",
      "The number of light switches"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "terminology",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Environmental conditions (such as heat, moisture, or chemicals) are a critical factor in selecting the correct type and size of cable."
  },
  {
    "id": 4018,
    "question": "Why is a thicker cable usually required for high-power appliances like electric cookers?",
    "options": [
      "To provide a higher current-carrying capacity",
      "To make the cable easier to bend around corners",
      "To increase the voltage drop across the circuit",
      "To reduce the need for mechanical protection"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "current-rule",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "High-power appliances draw more current. Thicker cables have lower resistance and can carry more current without overheating."
  },
  {
    "id": 4019,
    "question": "If a cable is installed in a very hot loft, what is the most likely effect on the cable?",
    "options": [
      "It will struggle to dissipate its own heat",
      "The cable will physically shrink in length",
      "The voltage at the socket will increase",
      "The copper core will become a permanent magnet"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "environmental-conditions",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "When the surrounding environment is already hot, the cable cannot get rid of the heat it generates as easily, meaning it may need to be larger to compensate."
  },
  {
    "id": 4020,
    "question": "What is the term used to describe the loss of electrical pressure as it travels down a long cable?",
    "options": [
      "Voltage drop",
      "Current drain",
      "Resistance gain",
      "Power surge"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "voltage-rule",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Voltage drop is the reduction in voltage that occurs as electricity flows through the resistance of the cable conductors."
  },
  {
    "id": 4021,
    "question": "What happens to the heat generated by a cable if it is completely surrounded by thermal loft insulation?",
    "options": [
      "The heat is trapped, causing the cable to get hotter",
      "The insulation cools the cable by blocking sunlight",
      "The insulation increases the voltage of the circuit",
      "The insulation provides mechanical protection only"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "environmental-conditions"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Thermal insulation is designed to stop heat from moving. If a cable is buried in it, the heat produced by the current cannot escape, leading to higher temperatures."
  },
  {
    "id": 4022,
    "question": "When several cables are installed together in the same conduit or bunch, this is known as:",
    "options": [
      "Grouping",
      "Splicing",
      "Terminating",
      "Armouring"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "terminology",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Grouping refers to cables being run together. Because they all generate heat, they can cause each other to overheat if not accounted for during selection."
  },
  {
    "id": 4023,
    "question": "What must be provided for a cable if it is installed in an area where it is likely to be hit or crushed?",
    "options": [
      "Mechanical protection",
      "A longer length of cable",
      "Higher voltage supply",
      "A different color insulation"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "discrimination",
      "health-safety"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Mechanical protection (like conduit, trunking, or steel wire armour) protects the cable from physical damage from tools, machinery, or impacts."
  },
  {
    "id": 4024,
    "question": "Why does 'grouping' cables together often mean they need to be larger or carry less current?",
    "options": [
      "Multiple cables generate more heat in a small space",
      "The cables will magnetically stick together",
      "Electricity leaks from one cable to another",
      "It is harder to identify the colors when grouped"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "current-rule"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "When cables are grouped, the heat from one cable warms the others. To prevent damage, the amount of current each can carry must be reduced."
  },
  {
    "id": 4025,
    "question": "A very long cable run to a garden shed is most likely to suffer from which specific problem?",
    "options": [
      "Excessive voltage drop",
      "Increased frequency of the AC supply",
      "Loss of mechanical protection",
      "Incorrect insulation resistance"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_FREQUENCY_WITH_VOLTAGE",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "voltage-rule",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "The longer the cable, the higher the total resistance. This results in a greater voltage drop, which might mean equipment at the end of the cable won't work correctly."
  },
  {
    "id": 4026,
    "question": "What is the primary danger to an electrical cable if it is carrying more current than it was designed for?",
    "options": [
      "The cable will overheat and the insulation may fail",
      "The cable will become highly magnetic and attract metal",
      "The voltage at the end of the cable will increase",
      "The cable will shrink in length due to the current"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "terminology",
      "health-safety"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "The main limiting factor for any cable is heat. If a cable carries too much current, it generates excess heat which can damage or melt the insulation."
  },
  {
    "id": 4027,
    "question": "Which term describes the loss of electrical pressure that occurs as electricity travels along the length of a cable?",
    "options": [
      "Voltage drop",
      "Current-carrying capacity",
      "Mechanical protection",
      "Cable grouping"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "discrimination",
      "units",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Voltage drop is the reduction in voltage as it moves from the source through the conductors to the load, usually caused by the resistance of the cable."
  },
  {
    "id": 4028,
    "question": "Why must an electrician consider 'grouping' when choosing a cable size?",
    "options": [
      "Cables run together trap heat and can cause each other to get hotter",
      "Cables run together will cause the circuit breaker to trip instantly",
      "Grouping cables makes the total voltage of the circuit increase",
      "Cables must be grouped to prevent them from vibrating"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "explanation",
      "grouping"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "When cables are grouped together, they cannot dissipate heat as easily. This means they may need to be larger to handle the same amount of current safely."
  },
  {
    "id": 4029,
    "question": "If a cable is being installed in a workshop where it is likely to be hit by heavy tools or machinery, which factor is most important?",
    "options": [
      "Mechanical protection",
      "Voltage drop",
      "The color of the insulation",
      "The frequency of the supply"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "OTHER",
      "3": "CONFUSED_FREQUENCY_WITH_VOLTAGE"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "health-safety",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Mechanical protection involves choosing a cable type (like SWA) or a containment system (like steel conduit) that can withstand physical damage."
  },
  {
    "id": 4030,
    "question": "How does surrounding a cable with thick thermal insulation in a loft affect its selection?",
    "options": [
      "The cable may need to be larger because the insulation traps heat",
      "The cable can be smaller because it is kept warm",
      "The insulation will increase the voltage in the cable",
      "The insulation has no effect on the cable size"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "discrimination",
      "explanation",
      "conceptual"
    ],
    "learningOutcomeId": "203-3L5C-LO3",
    "answerType": "mcq",
    "difficulty": 1,
    "estimatedTime": 45,
    "explanation": "Thermal insulation acts as a blanket, preventing heat from escaping the cable. To prevent the cable from overheating, a larger cross-sectional area is often required."
  },
  {
    "id": 4031,
    "question": "What is the primary safety risk if an electrical cable is selected with a cross-sectional area that is too small for the connected load?",
    "options": [
      "The cable insulation may overheat and fail",
      "The circuit breaker will refuse to reset",
      "The voltage at the appliance will increase",
      "The cable will become permanently magnetized"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "calculation",
      "explanation",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "If a cable is too small for the current flowing through it, the resistance causes excessive heat which can melt the insulation and lead to a fire."
  },
  {
    "id": 4032,
    "question": "Which of the following selection factors is most directly affected by the total length of a cable run from the source to the equipment?",
    "options": [
      "Voltage drop",
      "Mechanical protection",
      "Grouping factors",
      "Type of circuit breaker"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "voltage-rule",
      "conceptual"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "The longer a cable is, the more resistance it has, which leads to a loss of voltage (voltage drop) by the time it reaches the appliance."
  },
  {
    "id": 4033,
    "question": "An electrician is installing a cable through a loft space packed with thick thermal insulation. Why might the cable need to be larger than one installed in open air?",
    "options": [
      "The thermal insulation traps heat around the cable",
      "The insulation increases the resistance of the copper",
      "The insulation causes the voltage to drop faster",
      "The cable needs to be heavier to stay in place"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 90,
    "explanation": "Thermal insulation is designed to keep heat in; if it surrounds a cable, the heat generated by the current cannot escape, requiring a larger cable to reduce heat buildup."
  },
  {
    "id": 4034,
    "question": "When several cables are bunched together in the same trunking, they are 'grouped'. What effect does this have on their ability to carry current?",
    "options": [
      "It reduces their ability to dissipate heat",
      "It increases the voltage available to each circuit",
      "It makes the cables more resistant to physical damage",
      "It prevents the cables from vibrating"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Cables generate heat when in use. When grouped together, the heat from one cable warms the others, meaning they cannot carry as much current as they could individually."
  },
  {
    "id": 4035,
    "question": "Which term describes the maximum amount of current a cable can safely carry continuously without its insulation reaching an unsafe temperature?",
    "options": [
      "Current-carrying capacity",
      "Voltage drop limit",
      "Mechanical endurance",
      "Nominal frequency"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "terminology",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 45,
    "explanation": "Current-carrying capacity (often called Iz in regulations) is the safe limit of current for a specific cable under specific conditions."
  },
  {
    "id": 4036,
    "question": "A cable is being installed in a factory where it may be hit by moving machinery. Which factor is the electrician primarily addressing by choosing SWA (Steel Wire Armoured) cable?",
    "options": [
      "Mechanical protection",
      "Voltage drop",
      "Current-carrying capacity",
      "Ambient temperature"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Mechanical protection refers to the cable's ability to withstand physical impact, crushing, or abrasion."
  },
  {
    "id": 4037,
    "question": "If a power tool plugged into a very long extension lead fails to start or runs slowly, but the cable is not getting hot, what is the most likely issue?",
    "options": [
      "Excessive voltage drop",
      "The cable is too thick",
      "The grouping factor is too high",
      "The cable has too much mechanical protection"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "conceptual",
      "voltage-rule"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 90,
    "explanation": "Even if a cable is thick enough not to overheat, if it is too long, the voltage drop will mean the tool doesn't receive enough power to operate correctly."
  },
  {
    "id": 4038,
    "question": "Which of these is considered an 'environmental condition' that must be checked before selecting a cable type?",
    "options": [
      "Presence of water or high humidity",
      "The total cost of the installation",
      "The color of the consumer unit",
      "The age of the electrician"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "discrimination",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 45,
    "explanation": "Environmental conditions include factors like moisture, heat, sunlight (UV), and corrosive substances that could damage the cable."
  },
  {
    "id": 4039,
    "question": "Why is 'ambient temperature' a critical factor in cable selection?",
    "options": [
      "It affects how easily the cable can get rid of its own heat",
      "It changes the frequency of the AC supply",
      "It determines the color of the cable outer sheath",
      "It increases the voltage produced by the source"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_FREQUENCY_WITH_VOLTAGE",
      "2": "OTHER",
      "3": "CONFUSED_I_V_R"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "If the surrounding (ambient) air is already hot, the cable cannot release its own heat as effectively, meaning it will reach its maximum safe temperature sooner."
  },
  {
    "id": 4040,
    "question": "In general, if an installation environment becomes more difficult (e.g., higher heat or more cables grouped together), what usually happens to the required cable size?",
    "options": [
      "The cable size must be increased",
      "The cable size must be decreased",
      "The cable size stays the same but the fuse is removed",
      "The cable must be changed from copper to aluminum"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "To compensate for factors that cause extra heat or prevent heat from escaping, we use a larger cable which has lower resistance and stays cooler."
  },
  {
    "id": 4041,
    "question": "What is the primary safety risk when an electrical cable carries more current than its design limit?",
    "options": [
      "The cable will overheat and damage the insulation",
      "The voltage will increase and damage the equipment",
      "The copper conductors will become brittle immediately",
      "The magnetic field will disappear and stop the current flow"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "CONFUSED_AC_DC_SOURCES"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "current-rule",
      "conceptual",
      "units"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "The main danger of overcurrent is heat. If a cable carries more current than its capacity, the resistance in the wire generates heat that can melt the PVC insulation and cause a fire."
  },
  {
    "id": 4042,
    "question": "Which of the following factors specifically relates to the physical damage a cable might face from tools, heavy objects, or impact?",
    "options": [
      "Mechanical protection",
      "Current-carrying capacity",
      "Environmental conditions",
      "Voltage drop"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "TOPOLOGY_CONFUSION",
      "3": "CONFUSED_I_V_R"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "terminology",
      "discrimination",
      "health-safety"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Mechanical protection refers to the use of conduit, trunking, or armoured cable to prevent physical damage to the conductors."
  },
  {
    "id": 4043,
    "question": "An electrician is running a cable through a loft packed with thick thermal insulation. How does this affect the cable selection process?",
    "options": [
      "A larger cable is needed because heat cannot escape easily",
      "A smaller cable can be used because the insulation keeps it warm",
      "The cable length must be shortened to prevent voltage drop",
      "The insulation provides mechanical protection so a smaller cable is fine"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "DIVIDED_INSTEAD",
      "2": "TOPOLOGY_CONFUSION",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "application",
      "current-rule",
      "calculation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 90,
    "explanation": "Thermal insulation traps heat. If the heat generated by the cable cannot dissipate into the air, the cable will get hotter, so a larger conductor size is required to reduce the heat produced."
  },
  {
    "id": 4044,
    "question": "Why does 'grouping' cables together in a single conduit or trunking require careful cable selection?",
    "options": [
      "The combined heat from all cables reduces their individual current capacity",
      "The cables will magnetically attract each other and cause vibration",
      "It increases the total voltage available to the circuit",
      "It makes the cables easier to pull through the conduit"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_AC_DC_SOURCES",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "conceptual",
      "current-rule",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "When cables are grouped, they share heat. This 'grouping factor' means each cable can carry less current than if it were installed on its own."
  },
  {
    "id": 4045,
    "question": "If a piece of equipment is failing to start correctly because the cable run is very long, which selection factor was likely ignored?",
    "options": [
      "Voltage drop",
      "Mechanical protection",
      "Grouping factors",
      "Current-carrying capacity"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "TOPOLOGY_CONFUSION",
      "3": "CONFUSED_I_V_R"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "discrimination",
      "voltage-rule",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Voltage drop increases with the length of the cable. If the run is too long, the voltage at the end may be too low for the equipment to function."
  },
  {
    "id": 4046,
    "question": "A cable is installed in a commercial kitchen where it is exposed to high ambient temperatures and steam. This is an example of which selection factor?",
    "options": [
      "Environmental conditions",
      "Voltage drop",
      "Current-carrying capacity",
      "Grouping"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "TOPOLOGY_CONFUSION"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "application",
      "terminology",
      "health-safety"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Environmental conditions include ambient temperature, moisture, and presence of chemicals, all of which dictate the type and size of cable needed."
  },
  {
    "id": 4047,
    "question": "What is the correct definition of 'current-carrying capacity' in cable selection?",
    "options": [
      "The maximum current a cable can carry safely without overheating",
      "The total amount of voltage a cable can store within its insulation",
      "The physical weight of the copper conductors inside the cable",
      "The speed at which electrons travel through the wire"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "conceptual",
      "terminology",
      "current-rule"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "Current-carrying capacity (Iz) is the maximum current that a cable can carry continuously under specified conditions without its steady-state temperature exceeding a specified value."
  },
  {
    "id": 4048,
    "question": "Which action is most appropriate if a cable is found to be running too hot because it is grouped with many other cables?",
    "options": [
      "Use a larger cable size or separate the cables",
      "Increase the fuse size to allow the circuit to handle more heat",
      "Use a longer cable to help spread the heat over a larger area",
      "Switch the circuit from an AC supply to a DC supply"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "FORMULA_NOT_REARRANGED",
      "2": "DIVIDED_INSTEAD",
      "3": "CONFUSED_AC_WITH_DC"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "application",
      "current-rule",
      "health-safety"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 90,
    "explanation": "To reduce heat, you can either separate the cables (reducing the grouping factor) or use a larger cable size, which has lower resistance and handles heat better."
  },
  {
    "id": 4049,
    "question": "A 100-meter cable is used to power a garden shed. Even though the load is small, the lights inside appear dim. What is the most likely cause?",
    "options": [
      "Excessive voltage drop due to the long cable run",
      "The cable has too much mechanical protection",
      "The cable is too thick for the current being used",
      "Magnetic interference from the earth is slowing the current"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "DIVIDED_INSTEAD",
      "3": "CONFUSED_AC_DC_SOURCES"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "application",
      "voltage-rule",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 90,
    "explanation": "Voltage drop occurs over distance. Even with a small load, a very long cable can lose enough voltage to make lights appear dim or equipment fail."
  },
  {
    "id": 4050,
    "question": "When selecting a cable for a heavy industrial motor in a factory, why is 'mechanical protection' a high priority?",
    "options": [
      "To prevent the cable from being crushed or cut by machinery",
      "To stop the motor from drawing too much current from the mains",
      "To keep the voltage from dropping over long distances",
      "To ensure the cable remains flexible enough to move with the motor"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection Principles",
    "tags": [
      "conceptual",
      "health-safety",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 2,
    "estimatedTime": 60,
    "explanation": "In industrial environments, cables are at risk of physical damage. Mechanical protection (like SWA or steel conduit) is used to maintain the integrity of the insulation."
  },
  {
    "id": 4051,
    "question": "When selecting a cable for a new circuit, what is the primary safety concern that determines the minimum thickness of the conductor?",
    "options": [
      "The ability of the cable to dissipate heat without damaging the insulation",
      "The total weight of the cable to ensure the clips can hold it",
      "The color of the outer sheath to match the surrounding environment",
      "The flexibility of the copper to allow for easy bending around corners"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable selection principles",
    "tags": [
      "discrimination",
      "terminology"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "Heat is the main limiting factor in cable selection. If a cable cannot dissipate heat effectively, the insulation will degrade and potentially cause a fire."
  },
  {
    "id": 4052,
    "question": "Why does 'grouping' cables together in a single conduit usually require the electrician to select a larger cable size than if the cables were run separately?",
    "options": [
      "Cables bundled together trap heat, making it harder for each cable to stay cool",
      "Multiple cables in one pipe create a magnetic field that slows down the current",
      "The voltage in each cable increases when they are placed close to each other",
      "The physical friction between the cables increases the electrical resistance"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable selection principles",
    "tags": [
      "conceptual",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "Grouping cables reduces their ability to dissipate heat into the air. To prevent overheating, the cables must be de-rated or sized larger to carry the same current safely."
  },
  {
    "id": 4053,
    "question": "An electrician is running a cable to a remote garage 50 metres away. Even though the power load is small, they choose a much thicker cable than usual. Which factor is most likely driving this decision?",
    "options": [
      "Voltage drop",
      "Mechanical protection",
      "Magnetic interference",
      "Grouping factors"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "TOPOLOGY_CONFUSION",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable selection principles",
    "tags": [
      "application",
      "voltage-rule"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "Over long distances, voltage is lost along the length of the cable (voltage drop). To ensure equipment at the end receives enough voltage, a thicker conductor with lower resistance is used."
  },
  {
    "id": 4054,
    "question": "If a cable is installed in a location where it is completely surrounded by thermal loft insulation, what is the most likely risk if the circuit is used at full capacity?",
    "options": [
      "The cable will overheat because the insulation traps the heat generated by the current",
      "The cable will lose voltage because the insulation absorbs the electricity",
      "The circuit breaker will trip immediately because the insulation is conductive",
      "The cable will become too cold and the copper will become brittle"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "OTHER",
      "3": "SIGN_ERROR"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable selection principles",
    "tags": [
      "conceptual",
      "explanation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "Thermal insulation is designed to trap heat. When it surrounds a cable, it prevents heat from escaping, which can lead to the cable insulation melting or catching fire."
  },
  {
    "id": 4055,
    "question": "Which of the following scenarios describes a need for increased 'mechanical protection' for a wiring system?",
    "options": [
      "A cable being installed at a low level in a busy warehouse where forklift trucks operate",
      "A cable being installed in a high-temperature boiler room",
      "A cable being installed in a very long straight run across a ceiling",
      "A cable being installed inside a plastic trunking in a domestic bedroom"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "FORMULA_NOT_REARRANGED",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable selection principles",
    "tags": [
      "application",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 3,
    "estimatedTime": 75,
    "explanation": "Mechanical protection refers to shielding the cable from physical damage, such as impacts or crushing. A warehouse with forklifts presents a high risk of physical damage."
  },
  {
    "id": 4056,
    "question": "An electrician is installing a power circuit for a high-load kiln in a pottery studio. Why is the 'current-carrying capacity' the most critical factor to consider during cable selection for this specific appliance?",
    "options": [
      "The high current generates heat that can degrade the cable's insulation if the conductor is too small.",
      "The high current will cause the voltage to increase beyond the appliance's rated limit.",
      "A smaller cable would cause the electricity to flow too fast, damaging the kiln's heating elements.",
      "The magnetic field produced by the high current will physically pull the cable out of its wall fixings."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "CONFUSED_TERMINOLOGY",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "calculation",
      "conceptual",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 5,
    "estimatedTime": 120,
    "explanation": "Current flowing through a conductor generates heat. If the cable is too small for the load (current), the heat cannot dissipate quickly enough, leading to insulation failure and potential fire."
  },
  {
    "id": 4057,
    "question": "A new workshop is being built 60 meters away from the main distribution board. Even if the cable is rated to handle the required current, what specific factor might force the electrician to select an even larger cable size?",
    "options": [
      "Voltage drop along the length of the run could prevent equipment from operating correctly.",
      "The resistance of a long cable will cause the supply frequency to drop below 50Hz.",
      "A longer cable requires a larger cross-section to prevent the weight of the cable from snapping it.",
      "Longer cables naturally attract more static electricity from the environment, requiring thicker insulation."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_FREQUENCY_WITH_VOLTAGE",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "voltage-rule",
      "application",
      "calculation"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 4,
    "estimatedTime": 120,
    "explanation": "Voltage drop increases with the length of the cable. If the run is long, a larger conductor is often needed to reduce resistance and ensure the voltage at the end of the run remains within acceptable limits."
  },
  {
    "id": 4058,
    "question": "When twenty separate power cables are installed tightly together inside a single plastic trunking, why must their allowable current-carrying capacity be reduced?",
    "options": [
      "Grouping cables prevents heat from escaping, leading to a higher collective temperature.",
      "The magnetic fields from the cables will combine and push the current back toward the source.",
      "The total voltage of the system is shared between all cables in the group, reducing individual power.",
      "Grouping cables increases the physical friction of the electrons moving through the copper."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "USED_SERIES_RULE",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "parallel",
      "conceptual",
      "application"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 5,
    "estimatedTime": 120,
    "explanation": "Grouping cables reduces the ability of each individual cable to dissipate heat into the surrounding air. To prevent overheating, the cables must be 'de-rated' (treated as having a lower capacity)."
  },
  {
    "id": 4059,
    "question": "Which selection factor is most relevant when an electrician is installing a cable across a factory floor where heavy forklift trucks are frequently operated?",
    "options": [
      "Mechanical protection",
      "Voltage drop",
      "Grouping and spacing",
      "Current-carrying capacity"
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_TERMINOLOGY",
      "2": "TOPOLOGY_CONFUSION",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "health-safety",
      "application",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 4,
    "estimatedTime": 120,
    "explanation": "Cables in areas where they are subject to impact, crushing, or vibration must have adequate mechanical protection (e.g., steel wire armour or heavy-duty conduit) to prevent damage to the insulation."
  },
  {
    "id": 4060,
    "question": "A cable is installed in a loft space and is completely covered by 300mm of thermal glass-fibre insulation. What is the primary concern for the electrician regarding this installation?",
    "options": [
      "The thermal insulation will trap heat generated by the cable, significantly reducing its safe current limit.",
      "The glass-fibre insulation will react chemically with the cable and dissolve the copper core.",
      "The thermal insulation will increase the resistance of the circuit, causing the circuit breaker to trip instantly.",
      "The cable will become too cold because the loft insulation prevents the house heat from reaching it."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "application",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 5,
    "estimatedTime": 120,
    "explanation": "Thermal insulation is designed to stop heat transfer. When a cable is buried in it, the heat produced by the current cannot escape, which can lead to rapid overheating unless the cable size is increased."
  },
  {
    "id": 4061,
    "question": "How does an increase in the ambient (room) temperature affect the choice of cable for a standard lighting circuit?",
    "options": [
      "A larger cable may be required because the cable starts at a higher temperature and can reach its safety limit faster.",
      "A smaller cable can be used because heat helps electricity flow more easily through copper.",
      "The cable size remains the same, but the voltage must be increased to push through the warm air.",
      "The cable must be replaced with a DC-rated cable because AC cables cannot function in high temperatures."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_I_V_R",
      "3": "CONFUSED_AC_WITH_DC"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "conceptual",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 4,
    "estimatedTime": 120,
    "explanation": "If the environment is already hot (e.g., a boiler room), the cable has less 'headroom' for the heat it generates itself. Therefore, its current-carrying capacity is reduced, often requiring a larger conductor."
  },
  {
    "id": 4062,
    "question": "What is the consequence of a 'voltage drop' that exceeds the limits set by the IET Wiring Regulations?",
    "options": [
      "Appliances such as motors or LED drivers may fail to start, run inefficiently, or overheat.",
      "The electricity will begin to flow backward toward the consumer unit to find more pressure.",
      "The cable insulation will change color to indicate that the voltage is too low.",
      "The circuit breaker will detect the low voltage and trip immediately to protect the cable."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "voltage-rule",
      "conceptual"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 4,
    "estimatedTime": 120,
    "explanation": "Electrical equipment is designed to operate at a specific voltage. If the voltage drops too much due to cable resistance, the equipment may malfunction or suffer internal damage."
  },
  {
    "id": 4063,
    "question": "An electrician is selecting a cable for a 10kW electric shower. Which two factors are most likely to dictate the final cable size?",
    "options": [
      "Current-carrying capacity and whether the cable is buried in thermal insulation.",
      "The color of the outer sheath and the number of switches in the circuit.",
      "The frequency of the supply and the type of fuse board being used.",
      "The magnetic permeability of the walls and the height of the shower head."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "CONFUSED_FREQUENCY_WITH_CURRENT",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 5,
    "estimatedTime": 120,
    "explanation": "A 10kW shower draws a very high current, making current-carrying capacity vital. Because shower cables often run through lofts, the presence of thermal insulation is a major factor in preventing overheating."
  },
  {
    "id": 4064,
    "question": "In the context of cable selection, what does 'environmental conditions' primarily refer to?",
    "options": [
      "External factors like ambient temperature, presence of water, or exposure to sunlight.",
      "The amount of carbon dioxide produced by the electrical installation during use.",
      "The noise level generated by the electricity as it travels through the conduit.",
      "Whether the electricity was generated by solar panels or a coal power station."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "OTHER",
      "2": "OTHER",
      "3": "CONFUSED_TERMINOLOGY"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "terminology",
      "discrimination"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 4,
    "estimatedTime": 120,
    "explanation": "Environmental conditions include any external factor (heat, moisture, UV light, chemicals) that could affect the performance, safety, or lifespan of the cable and its insulation."
  },
  {
    "id": 4065,
    "question": "Synthesis Scenario: A long cable run is required for a large motor in a hot factory, and it must be installed alongside many other cables in a single tray. Which statement best describes the selection process?",
    "options": [
      "The cable must be significantly oversized to account for heat from the environment, heat from grouping, and voltage drop from the length.",
      "The cable can be small because the high temperature of the factory will lower the resistance of the copper.",
      "Voltage drop is the only concern, as the grouping of cables actually helps them cool down each other.",
      "The motor will automatically adjust the voltage, so only the mechanical protection of the cable tray matters."
    ],
    "correctAnswer": 0,
    "misconceptionCodes": {
      "1": "CONFUSED_I_V_R",
      "2": "OTHER",
      "3": "OTHER"
    },
    "section": "Installation 2365 Level 2",
    "category": "Cable Selection",
    "tags": [
      "application",
      "conceptual",
      "voltage-rule"
    ],
    "learningOutcomeId": "203-3L5C-LO1",
    "answerType": "mcq",
    "difficulty": 5,
    "estimatedTime": 120,
    "explanation": "This scenario combines three 'de-rating' or 'sizing' factors: high ambient temperature, grouping with other cables, and a long run (voltage drop). All three require the cable to be larger than a standard installation would require."
  }
];
