import type {
  GuidedChunkGenerationInput,
  GuidedChunkGenerationMemory,
  GuidedChunkLoScaffold,
  GuidedChunkScaffoldChunk,
} from '@/lib/generation/guidedChunk/types';
import { getGuidedChunkCurriculumProfile } from '@/lib/generation/guidedChunk/profiles';

export function buildGuidedChunkPlanPrompt(input: GuidedChunkGenerationInput): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are generating a guided-chunk lesson plan for a tutor-style runtime.',
    'The lesson must be grounded strictly in the provided source text.',
    'Output JSON only.',
    'Create a concise LO plan with chunk counts, key misconceptions, vocab, and assessment coverage.',
    'The runtime will teach in 80-150 word chunks, ask short recall questions, then a deeper question.',
    'Do not produce generic or meta teaching notes.',
    'Do not write prompts like "what is the main idea of this step".',
    'Plan for direct factual checks tied to the taught content.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.toneInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    `Lesson code: ${input.lessonCode}`,
    `Title: ${input.title}`,
    `Unit: ${input.unit}`,
    `Topic: ${input.topic}`,
    `Target audience: ${input.targetAudience ?? 'Beginner technical learner'}`,
    '',
    'Return JSON with this shape:',
    '{',
    '  "los": [',
    '    {',
    '      "loId": "string",',
    '      "loTitle": "string",',
    '      "successCriteria": ["string"],',
    '      "reviewHooks": ["string"],',
    '      "chunks": [',
    '        {',
    '          "chunkId": "string",',
    '          "learningGoal": "string",',
    '          "keyPoints": ["string"],',
    '          "misconceptionCodes": ["string"],',
    '          "vocab": [{ "term": "string", "definition": "string" }],',
    '          "assetSuggestion": "none|image",',
    '          "microbreakSuggestion": "none|classify-two-bins"',
    '        }',
    '      ],',
    '      "mcqFocus": ["string"],',
    '      "shortAnswerFocus": ["string"]',
    '    }',
    '  ]',
    '}',
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkFramePrompt(input: GuidedChunkGenerationInput, plan: unknown): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are generating a complete guided-chunk lesson frame for a tutor-style runtime.',
    'Output JSON only.',
    'Stay strictly inside the source text and plan.',
    'Each teachingCore must be 80-150 words and teach one main idea.',
    'Each chunk must include exactly 3 initial recall questions.',
    'Each chunk may include 1 deeper question.',
    'If you do not need an image or microbreak, set those fields to null.',
    'Do not create assessment items for untaught content.',
    'Do not include generator meta-talk inside teachingCore.',
    'Never write phrases such as "Focus on this idea", "This matters because", or "Keep in mind before answering".',
    'Initial recall questions must be direct factual or process questions, not meta questions about the lesson itself.',
    'MCQs must use plausible distractors from the same topic. Never use placeholder options such as "Irrelevant option" or "Another distractor".',
    'Repair templates must address the named misconception specifically.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.toneInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    `Lesson code: ${input.lessonCode}`,
    `Title: ${input.title}`,
    `Unit: ${input.unit}`,
    `Topic: ${input.topic}`,
    '',
    'Return a valid JSON object matching the GuidedChunkFrame shape used by the app.',
    'Use runtimeVersion "guided_chunk_v1" and a simple variantId ending in "-generated".',
    'Set metadata.author to "guided_chunk_generator".',
    'For any microbreakAfter value, use null for now unless the plan explicitly requires one.',
    '',
    'Plan JSON:',
    JSON.stringify(plan, null, 2),
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkLoScaffoldPrompt(
  input: GuidedChunkGenerationInput,
  lo: {
    loId?: string;
    loTitle?: string;
    successCriteria?: string[];
    reviewHooks?: string[];
    chunks?: Array<{
      chunkId?: string;
      learningGoal?: string;
      keyPoints?: string[];
      misconceptionCodes?: string[];
      vocab?: Array<{ term: string; definition: string }>;
      assetSuggestion?: string;
      microbreakSuggestion?: string;
    }>;
    mcqFocus?: string[];
    shortAnswerFocus?: string[];
  }
): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are generating an LO scaffold for a guided-chunk lesson generator.',
    'Output JSON only.',
    'The scaffold is generator-facing, not learner-facing.',
    'Define a clean non-overlapping chunk sequence for this LO.',
    'Each chunk must add something new.',
    'Use mustNotRepeat to stop later chunks from reteaching earlier chunks in full.',
    'Keep chunk goals concrete and narrow.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    `Lesson code: ${input.lessonCode}`,
    `Title: ${input.title}`,
    `Unit: ${input.unit}`,
    `Topic: ${input.topic}`,
    '',
    'Return JSON with this shape:',
    '{',
    '  "loId": "string",',
    '  "loTitle": "string",',
    '  "successCriteria": ["string"],',
    '  "reviewHooks": ["string"],',
    '  "chunkBlueprints": [',
    '    {',
    '      "chunkId": "string",',
    '      "learningGoal": "string",',
    '      "mustTeach": ["string"],',
    '      "mustNotRepeat": ["string"],',
    '      "vocab": [{ "term": "string", "definition": "string" }],',
    '      "misconceptions": ["string"],',
    '      "deeperQuestionFocus": "string",',
    '      "assessmentTargets": ["string"],',
    '      "assetSuggestion": "none|image",',
    '      "microbreakSuggestion": "none|classify-two-bins"',
    '    }',
    '  ],',
    '  "endAssessmentFocus": ["string"]',
    '}',
    '',
    'LO plan JSON:',
    JSON.stringify(lo, null, 2),
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkChunkPrompt(
  input: GuidedChunkGenerationInput,
  scaffold: GuidedChunkLoScaffold,
  chunk: GuidedChunkScaffoldChunk,
  memory: GuidedChunkGenerationMemory,
  priorChunkTexts: string[]
): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  const cg2365PromptRules =
    input.curriculum === 'cg2365'
      ? [
          'For C&G 2365, open by naming the electrical thing and what it does or how it differs in practice.',
          'Bad opening example: "This step links the earthing arrangement to the ADS parts..."',
          'Bad opening example: "You need to identify the main earthing system types..."',
          'Good opening example: "The first difference between TT, TN-S, and TN-C-S is how the installation gets its earth path."',
          'Good opening example: "In TT the installation relies on its own earth electrode, while in TN systems the supplier provides the earth path."',
          'Do not restate the title or learning goal inside the teachingCore.',
        ]
      : [];
  return [
    'You are generating one chunk for a guided-chunk tutor lesson.',
    'Output JSON only.',
    'Generate only the current chunk.',
    'Do not restate earlier chunks except for one brief linking phrase if needed.',
    'Do not include meta teaching language.',
    'Teaching core must be 80-150 words and cover one main idea only.',
    'The teaching core must read like a live tutor explanation, not a textbook note or mnemonic dump.',
    'Include exactly 3 initial recall questions and 1 deeper question.',
    'Recall questions must test the current chunk, not prior chunks.',
    'Repair templates must match the current chunk misconceptions.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.toneInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    ...cg2365PromptRules,
    input.lessonProfileNotes ?? '',
    '',
    `Lesson code: ${input.lessonCode}`,
    `LO: ${scaffold.loTitle}`,
    `Current chunk: ${chunk.chunkId}`,
    `Current goal: ${chunk.learningGoal}`,
    '',
    'Already covered concepts:',
    JSON.stringify(memory.coveredConcepts, null, 2),
    '',
    'Already introduced vocab:',
    JSON.stringify(memory.introducedVocab, null, 2),
    '',
    'Already handled misconceptions:',
    JSON.stringify(memory.handledMisconceptions, null, 2),
    '',
    'Prior chunk texts in this LO:',
    JSON.stringify(priorChunkTexts, null, 2),
    '',
    'Current chunk blueprint:',
    JSON.stringify(chunk, null, 2),
    '',
    'Return JSON with this shape:',
    '{',
    '  "chunkId": "string",',
    '  "learningGoal": "string",',
    '  "teachingCore": "string",',
    '  "vocabPack": [{ "term": "string", "definition": "string" }],',
    '  "initialRecallQuestions": [',
    '    { "id": "string", "prompt": "string", "expectedConcepts": ["string"] }',
    '  ],',
    '  "candidateFollowUpModes": ["probe", "repair"],',
    '  "candidateDeeperQuestion": { "id": "string", "prompt": "string", "expectedConcepts": ["string"] },',
    '  "misconceptionCodes": ["string"],',
    '  "repairTemplates": [',
    '    {',
    '      "misconceptionCode": "string",',
    '      "shortCorrection": "string",',
    '      "contrastPrompt": "string",',
    '      "retryPrompt": "string"',
    '    }',
    '  ],',
    '  "assetInjection": null,',
    '  "microbreakAfter": null',
    '}',
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkLoAssessmentPrompt(
  input: GuidedChunkGenerationInput,
  scaffold: GuidedChunkLoScaffold,
  chunkTexts: string[]
): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are generating LO-end assessments for a guided-chunk lesson.',
    'Output JSON only.',
    'Assess only concepts explicitly taught in the final chunk set.',
    'Do not assess untaught content.',
    'Use plausible distractors from the same topic.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    `Lesson code: ${input.lessonCode}`,
    `LO: ${scaffold.loTitle}`,
    '',
    'Assessment focus:',
    JSON.stringify(scaffold.endAssessmentFocus, null, 2),
    '',
    'Final chunk texts for this LO:',
    JSON.stringify(chunkTexts, null, 2),
    '',
    'Return JSON with this shape:',
    '{',
    '  "loTestMcq": {',
    '    "intro": "string",',
    '    "mcqs": [',
    '      { "id": "string", "prompt": "string", "options": ["string"], "correctIndex": 0, "explanation": "string" }',
    '    ],',
    '    "shortAnswers": []',
    '  },',
    '  "loTestShortAnswer": {',
    '    "intro": "string",',
    '    "mcqs": [],',
    '    "shortAnswers": [',
    '      { "id": "string", "prompt": "string", "expectedConcepts": ["string"] }',
    '    ]',
    '  }',
    '}',
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkScorePrompt(
  input: Pick<GuidedChunkGenerationInput, 'curriculum' | 'lessonProfileNotes' | 'sourceText'>,
  frame: unknown
): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are scoring a guided-chunk lesson frame for a tutor-style runtime.',
    'Return JSON only.',
    'Score it using the same pedagogical priorities as the main V1 lesson pipeline.',
    'Judge learner-facing teaching quality, not just schema completeness or technical correctness.',
    'Use this rubric exactly:',
    '- beginnerClarity (0-30): plain language, concrete explanation, direct definition, misconception handling, readable first-turn teaching',
    '- teachingBeforeTesting (0-25): the answer is taught before any question, progression is teach then recall then deeper check, no cold questions',
    '- markingRobustness (0-20): expectedConcepts are specific and gradeable, question scope matches answer scope, repair is usable',
    '- alignmentToLO (0-15): content and checks align to the intended LO or chunk goal and do not drift into untaught material',
    '- questionQuality (0-10): concrete, useful, non-generic, non-meta, non-placeholder questions with sensible progression',
    'Penalize hard for generic openings, title restatement, placeholder setup text, note-like prose, overloaded first turns, and abstract questions such as "what is the key fact in this chunk".',
    'Scores must use integer values and the total must be between 0 and 100.',
    'Keep issues concise and action-oriented.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    'Return JSON with this shape:',
    '{',
    '  "breakdown": {',
    '    "beginnerClarity": 0,',
    '    "teachingBeforeTesting": 0,',
    '    "markingRobustness": 0,',
    '    "alignmentToLO": 0,',
    '    "questionQuality": 0',
    '  },',
    '  "summary": "string",',
    '  "refinementNotes": ["string"],',
    '  "issues": [',
    '    {',
    '      "category": "beginnerClarity|teachingBeforeTesting|markingRobustness|alignmentToLO|questionQuality",',
      '      "problem": "string",',
      '      "suggestion": "string"',
    '    }',
    '  ]',
    '}',
    '',
    'Frame JSON:',
    JSON.stringify(frame, null, 2),
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}

export function buildGuidedChunkRefinePrompt(
  input: GuidedChunkGenerationInput,
  frame: unknown,
  score: { summary: string; issues: Array<{ category: string; problem: string; suggestion: string }> }
): string {
  const curriculumProfile = getGuidedChunkCurriculumProfile(input.curriculum);
  return [
    'You are refining a guided-chunk lesson frame after scoring.',
    'Return JSON only.',
    'Rewrite the frame to improve learner-facing quality without changing the curriculum scope.',
    'Fix every issue listed below.',
    'Do not include generator meta-talk in teachingCore.',
    'Do not let the teaching core read like standards notes, glossary notes, or etymology commentary.',
    'Use direct factual recall questions, not meta questions about the lesson.',
    'Use natural deeper questions.',
    'Repair templates must sound like a tutor, not an internal validator.',
    'Short-answer expectedConcepts must contain concise answer points, not copies of the prompt.',
    'MCQs must use plausible topic-relevant distractors.',
    curriculumProfile.audienceInstruction,
    curriculumProfile.toneInstruction,
    curriculumProfile.chunkInstruction,
    curriculumProfile.questionInstruction,
    input.lessonProfileNotes ?? '',
    '',
    'Score summary:',
    score.summary,
    '',
    'Issues to fix:',
    ...score.issues.map((issue, index) => `${index + 1}. [${issue.category}] ${issue.problem} Fix: ${issue.suggestion}`),
    '',
    'Current frame JSON:',
    JSON.stringify(frame, null, 2),
    '',
    'Source text:',
    input.sourceText,
  ].join('\n');
}
